// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ipv6AddressMode } from "./Ipv6AddressMode";

export type CreateMicroNetworkRequest = { name: string, subnetCidr: string, internetEnabled: boolean, uplink?: string | null, ipv6Cidr?: string | null, ipv6AddressMode?: Ipv6AddressMode, };
