// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EgressPolicy } from "./EgressPolicy";
import type { VmState } from "./VmState";

export type MicroNetworkVm = { id: string, name: string, state: VmState, ipv4: string | null, ipv6: string | null, egressPolicy: EgressPolicy, };
