// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
export type MicroNetworkNat = { enabled: boolean, uplink: string, sourceCidr: string, ipv6SourceCidr: string | null, };
