// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ipv6AddressMode } from "./Ipv6AddressMode";
import type { Ipv6EgressMode } from "./Ipv6EgressMode";

export type MicroNetworkSubnet = { cidr: string, gateway: string, usableAddresses: number, allocatedAddresses: number, dhcp: string, ipv6Cidr: string | null, ipv6Gateway: string | null, ipv6AddressMode: Ipv6AddressMode | null, ipv6Egress: Ipv6EgressMode | null, };
