// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SshHostKeyResponse = {
  /** SHA256:… fingerprint (`ssh-keygen -lf`). */
  fingerprint: string;
  /** OpenSSH public key line. */
  publicKey: string;
};
