// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EgressPolicy } from "./EgressPolicy";
import type { PortForward } from "./PortForward";
import type { ShellRef } from "./ShellRef";
import type { StartupStep } from "./StartupStep";
import type { StartupStepRun } from "./StartupStepRun";
import type { VmState } from "./VmState";
import type { VmUsageSample } from "./VmUsageSample";

export type VmResponse = {
  id: string;
  name: string;
  state: VmState;
  template: string;
  templateVersion: string;
  cpu: number;
  ram: number;
  diskGb: number;
  startupStep: StartupStep | null;
  startupTimeline: Array<StartupStepRun>;
  egressPolicy: EgressPolicy;
  ipv4: string | null;
  ipv6: string | null;
  mac: string | null;
  hostname: string;
  microNetworkId: string;
  storageRoot: string;
  /**
   * Guest OS CPU busy percent from the Metrics Agent (`FIRECRAB_USAGE cpu_pct=`).
   * null until the agent reports or the VM is not running.
   */
  cpuUsagePercent: number | null;
  /** Guest used memory MiB (MemTotal − MemAvailable); null until reported. */
  memoryUsedMib: number | null;
  /** Guest MemTotal MiB; null until reported. */
  memoryTotalMib: number | null;
  /** Guest used memory percent of MemTotal; null until reported. */
  memoryUsedPercent: number | null;
  /** Recent Metrics Agent samples for sparklines (oldest first, bounded). */
  usageHistory: Array<VmUsageSample>;
  /** Shell revisions pinned on this VM (injected on each start). */
  shellRefs?: Array<ShellRef>;
  /** Inbound port forwarding rules (DNAT). */
  portForwards?: Array<PortForward>;
  /** Per-VM environment. Empty is valid. Stored and applied in plaintext. */
  env?: { [key: string]: string };
  /** SHA256 fingerprint of the guest SSH host key; null until first start. */
  sshHostFingerprint?: string | null;
};
